### ISSUE TITLE
frequency.ItemSketch doesn't implement equals or hashCode

### ISSUE THREAD

**Issue by sszuflita** [DataSketches/sketches-core#140] opened 2017-03-30 22:09 UTC
Happy to submit a PR

**Comment by leerho** [comment] 2017-03-30 22:47
Overriding Object equals() and hashCode() does not make sense for sketches, which are stochastic data structures.  Could you please explain why you think you need this?

**Comment by sszuflita** [comment] 2017-03-30 23:18
I'm a bit confused; why does the stochastic nature of the data matter here?

I am serializing some sketches (nested within some of my own objects) and wrote a suite of back-compat tests. I wanted to verify that newly created objects equal the old deserialized objects.

**Comment by leerho** [comment] 2017-03-31 00:57
Sketches are stochastic / probabilistic structures: The sketches intentionally insert random noise into the process of building their internal data structures with the incoming data.  What this means is that even if you present two sketches with exactly the same input stream and in the same order, the internal data stored in the two sketches will not necessarily be the same, thus the results of the two sketches will not be exactly the same.  Even if you have two sketches that produce the same answer, it does not mean that they were both fed the same data. 

The only "guarantee" is that the result obtained from the sketch will be within some known error bounds with a specified confidence level -- when compared to the the brute-force computation of an exact result based on the entire input stream. 

So what does it mean to be equal?  What possible use would a overridden hashCode be if it is always different?

We do not provide equals() or hashCode() methods because in the general case, they make no sense, and depending on them could be very misleading.

However, for Theta Sketches, we do provide a `JaccardSimilarity` class that you could use in regression testing.  This returns a "similarity" value (between 0 and 1.0) and error bounds on that similarity value.  Please refer to the Javadocs.

For Quantiles sketches we will soon offer a Kolmogorov–Smirnov (K-S) test, which will measure the "similarity" of two distributions, but it has not been released yet.  But even this test can lead to significant false-positives in certain cases.

Frequent Items sketches are even more problematic.  Even if you rebuild a serialized FI sketch from the byte[] (obtained from toByteArray()), the internal hash tables will not be the same.  Only the heavy items are meaningful to compare and you have to consider variations caused by differences between the no-false-positives and no-false-negatives queries.

I understand your desire to want to do this, but the pros of these probabilistic algorithms is that they are so extremely fast and small.  One of the cons is that they are difficult to compare to each other as you want to do.

**Comment by sszuflita** [comment] 2017-04-03 16:05
I'd be fine with a very narrow definition of equal.

Building a dataset on the same stream doesn't guarantee equality. However, when the sketch has been built, it has some state (in this case, a byte array). It is important that we can reconstruct an equivalent sketch using that same bytearray so that these sketches can survive being written to disk, or being sent over the wire.

In my mind, if 

    Sketch sketch; // creation excluded, assume we use COMPARATOR
    byte[] data = sketch.toByteArray(new ArrayOfStringsSerDe());
    Sketch newSketch = ItemsSketch.getInstance(new NativeMemory(data), COMPARATOR,
                  new ArrayOfStringsSerDe()));

then sketch should equal newSketch. Similarly, I'd expect sketch to equal ItemsSketch.copy(sketch).

I'd also expect these objects to produce equal values for getFrequentItems (or is there non-determinism in that method that I'm missing?)

**Comment by leerho** [comment] 2017-04-19 19:55
If you want to validate the I/O transport layer, you can do that yourself by comparing the byte[] sent to the transport with the byte[] returned.  In many system environments the binary data may undergo multiple encoding and decoding (e.g. Base64), wrapping and unwrapping layers.  In working with multiple systems teams, we have come across a number of cases where the byte[] returned was corrupted during transport for all kinds of reasons.  For example, Hive, Pig and Spark all use very different transport mechanisms, so this is an important diagnostic check.  But this is outside the scope of the sketch library.

What you are asking for is the ability to test that the sketch reconstructed from the byte[] returned by the `toByteArray()` method will return exactly the same results.  But this can be tricky and depends on the specific sketch.  For FIS, for example, the list of items returned from the `getFrequentItems(...)` are sorted in estimated frequency order.  

There **is** a non-determinism issue here: Two different items with the same frequency may be output in different order, because the items may be reconstructed into the internal hash table in a different order and thus are presented to the sort in a different order. Thus, the total list of items should be the same but their order in the list may not be.  Writing a check for this may be OK for a diagnostic check, but not suitable for a built-in `.equals(...)` function because it is very expensive and could be easily be misused and misunderstood.  If you feel you really need this function you can write it without any knowledge of the internals of sketch.

Validating that the sketch is correctly doing its job and producing results within the error bounds is our job and with our unit tests, extensive external characterization tests, and supporting mathematical proofs, we would like to assure you that this is the case.  Nonetheless, if you think that a sketch is not performing properly, we would be grateful if you could submit a unit test that reproduces this behavior and we will gladly look into it.

I would hope we can close this issue?

**Closed** 2017-04-25 15:44 UTC
Labels: Discuss
